export interface Contact {
  id: string
  name: string
  email: string
  phone?: string
  company?: string
  tags: string[]
  status: ContactStatus
  score: number
  createdAt: Date
  updatedAt: Date
  lastInteraction?: Date
  notes?: string
}

export type ContactStatus = 'cold' | 'warm' | 'hot'

export interface Deal {
  id: string
  title: string
  contactId: string
  value: number
  stage: DealStage
  createdAt: Date
  updatedAt: Date
  dueDate: Date
  description?: string
  probability: number
  isArchived: boolean
}

export type DealStage = 
  | 'prospect' 
  | 'engaged' 
  | 'meeting' 
  | 'proposal' 
  | 'won' 
  | 'lost'

export const DEAL_STAGES: Record<DealStage, { label: string; color: string; maxDays: number }> = {
  prospect: { label: 'Prospect', color: '#6B7280', maxDays: 30 },
  engaged: { label: 'Relation engagée', color: '#3B82F6', maxDays: 14 },
  meeting: { label: 'Rendez-vous pris', color: '#8B5CF6', maxDays: 7 },
  proposal: { label: 'Proposition en cours', color: '#F59E0B', maxDays: 21 },
  won: { label: 'Fermé - gagné', color: '#10B981', maxDays: 0 },
  lost: { label: 'Fermé - perdu', color: '#EF4444', maxDays: 0 }
}

export interface Task {
  id: string
  title: string
  description?: string
  contactId?: string
  dealId?: string
  type: TaskType
  status: TaskStatus
  priority: TaskPriority
  dueDate: Date
  createdAt: Date
  updatedAt: Date
  completedAt?: Date
  isAutoGenerated: boolean
}

export type TaskType = 'call' | 'email' | 'meeting' | 'follow-up' | 'other'
export type TaskStatus = 'pending' | 'completed' | 'snoozed'
export type TaskPriority = 'low' | 'medium' | 'high'

export interface User {
  id: string
  name: string
  email: string
  createdAt: Date
  settings: UserSettings
}

export interface UserSettings {
  theme: 'light' | 'dark'
  notifications: boolean
  reminderHours: number[]
  pipelineHealthThreshold: number
}

export interface PipelineStats {
  totalDeals: number
  totalValue: number
  avgDealValue: number
  avgTimePerStage: Record<DealStage, number>
  conversionRates: Record<DealStage, number>
  healthScore: number
  expiredDealsPercentage: number
}

export interface OnboardingState {
  currentStep: number
  isCompleted: boolean
  hasCreatedContact: boolean
  hasCreatedDeal: boolean
  hasCreatedTask: boolean
}